### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by td512** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#1]
Heya, I'm trying to build this on Mac, but there are no real instructions on how to. The compilation exits in multiple places also

**Comment by purpl3F0x** [comment]
Have you installed Qt ?
Are you using terminal or any IDE to compile ?

**Comment by td512** [comment]
Qt5 is installed via brew, I updated the CMakeList to reflect brew's location, and I'm using a terminal to compile it with

`cmake . && make `

**Comment by purpl3F0x** [comment]
Ok, I think I got it.
- Firstly on CMakeLists.txt change `${PROJECT_NAME}` to `tidal-rpc`.
- Also you need to transfer the `icon.ico` into the assets folder.
- And move the discord libs folder on directory app (so project and discord-rpc folder are in the same dir) OR change line 93 in CMake by removing the`../`.

Let me know

**Comment by purpl3F0x** [comment]
I'm closing the issue since I got no response and I have provided a good enough solution to compile the code.
