### ISSUE TITLE
How can I port windows_api_hook.hh to linux

### ISSUE THREAD

**Issue by Jaydenha09** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#101]
I want to port it to linux but I can't find any document for it, anyone can provide me those document or you can give me the code for linux? thanks

**Comment by Jaydenha09** [comment]
I am using fedora wayland

**Comment by Jaydenha09** [comment]
maybe you can make it detect some browser activity, or something, but I cant find any document about these

**Comment by V3ntus** [comment]
This isn't possible due to the Windows API strictly being Windows exclusive (who would've thought). There's a Mac variation of this, I would start there

**Comment by ungive** [comment]
@Jaydenha09 Some useful links to implement this on Linux:
- MPRIS specification: https://www.freedesktop.org/wiki/Specifications/mpris-spec/
- MPRIS metadata fields: https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/
- playerctl C library, which can be used to read player metadata: https://github.com/altdesktop/playerctl
- If you don't want to use playerctl, you'll have to interface with DBUS directly

If you want a Discord status right now for TIDAL, here are some options:
- This port of TIDAL to Linux has a built-in Discord RPC; https://github.com/Mastermindzh/tidal-hifi
- Music Presence is an app that shows a Discord status for media from any media player: https://github.com/ungive/discord-music-presence. Disclaimer: I am the author and there is no stable Linux release right now, but you can join the Discord server, if you wanna help test the first Linux builds!
