### ISSUE TITLE
Change tidal to something else

### ISSUE THREAD

**Issue by Hackatoan** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#102]
Not sure how rich Prescence works, but was wondering if possible to switch from playing tidal to playing music or any other variation. Probably as some sort of config file.

![image](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/assets/62629253/377a6d1b-2de9-4103-8ba5-03be939ee7bf)

if impossible just close it.

**Comment by ungive** [comment]
Hey, I have modified the code of this application some time ago to do exactly that, but it has never been merged by the project author. You can the pull requst and some discussion regarding it here: #100 

You can still find the release/build I made that is mentioned in the above linked pull requested here: https://github.com/ungive/discord-music-presence/releases/tag/v.1.4.0-6. I archived the source code that was used to build it here: https://github.com/ungive/tidal-discord-presence. If you want to stick with this project, you can achieve what you want with my modifications, you can find some instructions on how to do it at the first link. Note that I do not maintain my fork of the project anymore.

I will also list some alternatives that I know of. Note that the first one is my own project.

- https://github.com/ungive/discord-music-presence
**This is my own project**, it's closed-source for the foreseeable future. There's a checkbox in the tray menu to switch between "Music" and the player name ("TIDAL"). There's also a configuration file in `%APPDATA%\Music Presence`, which allows you to overwrite the application ID, so you can use anything you want.
- https://github.com/BitesizedLion/TidalRPC
Open-source, does not have the functionality, but you might have luck opening an issue there.

**Comment by purpl3F0x** [comment]
Technically speaking, the merge request was deleted 🙂

**Comment by purpl3F0x** [comment]
Yes, If you'd like to. I have some free time, until the end of the week, so I could review it.
