### ISSUE TITLE
Rich presence shows for local client, does not show for other users

### ISSUE THREAD

**Issue by PandemicMojo** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#106]
My local client displays exactly as intended. No album art bugs, perfectly responsive, no crashes or issues. I'm manually starting both programs after boot. No matter what I do, the rich presence does not show for anyone else when they open my profile.

Things I've done:
Added RPC to games list - It displays only as either the current artist's name, or "TIDAL" if nothing is playing.
Restarted everything more than once - both programs, the entire PC, etc.
Opened Discord in web browser - this shows the correct info! I don't know if you implemented for it to work in web version as well, but I figured I would note this.
Opened Discord mobile (IOS) - It also shows correctly when Tidal is playing from my PC! I can see it when I'm signed in to the account on any device.
Tested launching the programs first then second, in both orders. Both produce exact same result, local works perfect, doesn't actually share info for other users to see.

Windows 10 Home 22H2 build 19045.4651
Tidal Desktop Client v2.37.8.59-release (W: 2024.08.28-107) (NP: 3.1.4.221)
RPC v1.3.0.114

My next steps to debug are:
Test running apps on startup - I doubt this will change the outcome
Test with older versions
Reinstall Discord
Test with different discord account/PC hardware/OS

My local client:
![Screenshot 2024-08-28 150004](https://github.com/user-attachments/assets/fd075809-c69d-4d7c-9af8-1a34cca5d0c0)
![Screenshot 2024-08-28 150049](https://github.com/user-attachments/assets/88d32c60-dc00-4b89-b26d-06ac7383590a)

Another user's POV:
![image2](https://github.com/user-attachments/assets/f33da158-5be0-4434-8500-4c36a13a5269)
![image](https://github.com/user-attachments/assets/b535d71c-5e5b-4565-82b0-025e0834ca93)

I can provide any other info if needed.

**Comment by purpl3F0x** [comment]
Hello, 
Adding the app to the list of games is no longer needed and probably causes more issues than it solves. Try removing it, and just let the rpc app auto-connect.

**Comment by PandemicMojo** [comment]
I thought I had tried that earlier, but upon removing TIDAL from the games list, and restarting RPC as admin, it works perfectly! Thank you so much!
