### ISSUE TITLE
errors on windows with v1.1.1

### ISSUE THREAD

**Issue by SweepsMT** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#11]
![image](https://user-images.githubusercontent.com/28968388/78923589-61a05c00-7a90-11ea-9c05-b45058c821e4.png)

![image](https://user-images.githubusercontent.com/28968388/78923617-6e24b480-7a90-11ea-8bf5-bae7f85f8969.png)

![image](https://user-images.githubusercontent.com/28968388/78923648-7846b300-7a90-11ea-9578-11b0e58c3607.png)

**Comment by purpl3F0x** [comment]
I know, I know... 
Download the 1.1.0 it's the same for Windows.

**Comment by purpl3F0x** [comment]
same as #9 
fixed on 3b349bf4b7bbfb41b9496cd57befe4514e898a97
