### ISSUE TITLE
Missing dlls.

### ISSUE THREAD

**Issue by DirtMattress** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#12]
When I tried running the program for the first time, I recieved this error.
`The program can't start because libwinpthread-1.dll is missing. Try reinstalling the program to fix the problem.`
I resolved that by adding the .dll to the Environment variables, which then produced the following error.
`The application was unable to start correctly (oxc000007b). Click OK to close the application.`

Basic googling seems to suggest that this is due to the application being build for 32-bit systems?

I am using a 64-bit system. Is there any workaround for this?

**Comment by DirtMattress** [comment]
Nevermind, I see the previous issues where you suggest going to an older version for the time being. This seems to have worked for me. 

You can close this . D:

**Comment by purpl3F0x** [comment]
I have updated the release to avoid any confusions.
