### ISSUE TITLE
Doesn't recognize songs playing in Tidal, on Windows

### ISSUE THREAD

**Issue by PaulBGD** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#14]
Not sure what info you need, I looked for a debug log or something and didn't find anything. I have Tidal playing with Discord open, but the application doesn't display anything but the name and the checked "Running" box in the menu. I've tried rebooting and toggling running on/off, but it doesn't seem to ever recognize songs.

RPC: v.1.1.1 
Tidal: 2.15.2.63 (W: 3.23.0-9-804966cca57a314124edc2a3526cb7cf14034ebb) (NP: 3.0.0.125)
Discord: Stable 58743 (e90b0d6)
Windows 10 64-Bit (10.0.18363)

**Comment by PaulBGD** [comment]
![image](https://user-images.githubusercontent.com/3516420/80171200-53356280-85af-11ea-8a51-66b3780250be.png)

It was this dang slider.. but now I'm in the middle of converting this app to use the new game sdk, so I'll PR in a bit,

**Comment by purpl3F0x** [comment]
Good, I wanted to change to the new api but ... not enough time 💩.
