### ISSUE TITLE
Wrong image

### ISSUE THREAD

**Issue by ForceBlood** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#16]
The image doesn't turn to the high-res version when playing a song with master audio quality.

**Comment by purpl3F0x** [comment]
The high res image is a hit or miss, cause the app only knows the title of the song you're playing not the exact track, so i searches tidal database. And peaks the first result (almost).
Can't do anything to fix it, which track is it tho ?

**Comment by ForceBlood** [comment]
It doesn't seem to be working on any of them for some reason. Example: Chills

**Comment by purpl3F0x** [comment]
idk, it was also kind of broken feature, so I will close the issue. 
But I will do some testing when I have time, cause i don't use the TIDAL app
