### ISSUE TITLE
cant launch on windows 10

### ISSUE THREAD

**Issue by pandemic20** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#18]
getting this error while trying to launch "tidal-rpc.exe" on windows
![Annotation 2020-04-26 051704](https://user-images.githubusercontent.com/64353837/80303318-7e6dac80-877d-11ea-9a5c-9899f49af269.png)

**Comment by purpl3F0x** [comment]
did you unzip the files ?

**Comment by alanman87** [comment]
I'm also seeing this issue after unzipping.

**Comment by pandemic20** [comment]
yes i did.  1.0 works.  1.2 or 1.1 does not.

**Comment by purpl3F0x** [comment]
I updated the release. Let me know

**Comment by pandemic20** [comment]
I see an update from 4 days ago? that's the 1.2 i was referring to.

**Comment by pandemic20** [comment]
redownloaded it just in case it was the one you were referring to and same error unfortunately

**Comment by purpl3F0x** [comment]
I will try to fix it tomorrow. You can use an older version there little to none difference

**Comment by purpl3F0x** [comment]
Check now, if you can. I updated the release

**Comment by pandemic20** [comment]
i am not seeing the updated release appear. https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL

**Comment by purpl3F0x** [comment]
I just updated the zip

**Comment by k3lt** [comment]
It's not fixed, still same error for me.

**Comment by alexmarques7** [comment]
Same error here.

![same-here](https://user-images.githubusercontent.com/12925122/80737187-8c0e9380-8ae9-11ea-92ba-83ea0f79bf59.png)

**Comment by purpl3F0x** [comment]
Any chance this works ? https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/releases/download/v.1.2/tidal-rpc-win64.zip 

🤞🤞

**Comment by Konack** [comment]
> Any chance this works ? https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/releases/download/v.1.2/tidal-rpc-win64.zip
> 
> 🤞🤞

Seem to be getting a different error now.
![Annotation 2020-04-30 153510](https://user-images.githubusercontent.com/16552064/80751652-3392c280-8af8-11ea-8faa-c31f1206e6bd.png)

**Comment by purpl3F0x** [comment]
Ooof I need to compile it with the Microsoft compiler 😩

**Comment by purpl3F0x** [comment]
@Konack you added the 64bit version a of the ddls right?

**Comment by Konack** [comment]
> @Konack you added the 64bit version a of the ddls right?

I made sure they were the 64but dlls

**Comment by purpl3F0x** [comment]
Ok thanks for the info 👍

**Comment by purpl3F0x** [comment]
Should be fixed on 1.2.1. Plz let me know

**Comment by k3lt** [comment]
> Should be fixed on 1.2.1. Plz let me know

Seems to be working fine now, thanks. :)
