### ISSUE TITLE
Windows Errors - Missing DLLs for 1.2

### ISSUE THREAD

**Issue by alanman87** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#19]
I receive these errors when launching version 1.2

![image](https://user-images.githubusercontent.com/28031959/80433980-81c07f80-88c6-11ea-9041-40f85ef49617.png)
![image](https://user-images.githubusercontent.com/28031959/80338375-2b9dfe80-882a-11ea-8ba0-66bf456dbb5e.png)
![image](https://user-images.githubusercontent.com/28031959/80338343-16c16b00-882a-11ea-9fa1-cd7e44a0dc38.png)

**Comment by purpl3F0x** [comment]
wrong compiler my bad. I updated the zip

**Comment by purpl3F0x** [comment]
wrong compiler I think I fixed it.I updated the release.
Let me know

**Comment by alanman87** [comment]
1 of the 3 errors is now fixed. Still seeing these 2:
![image](https://user-images.githubusercontent.com/28031959/80433896-4d4cc380-88c6-11ea-816d-11604f2fb414.png)
![image](https://user-images.githubusercontent.com/28031959/80433907-550c6800-88c6-11ea-9514-2a437df21ba7.png)

**Comment by yukkerz** [comment]
I am having the same 2 errors.

**Comment by purpl3F0x** [comment]
check now plz

**Comment by yukkerz** [comment]
![Capture](https://user-images.githubusercontent.com/54380678/80640205-121ad380-8a31-11ea-9e3e-2010fb14b5e1.PNG)
Now I get this error.

**Comment by alanman87** [comment]
Receiving this error with 1.2
![image](https://user-images.githubusercontent.com/28031959/81319604-e6fe3880-905d-11ea-839f-9c073d99d779.png)
Hope this info helps.

**Comment by riuowo** [comment]
https://gyazo.com/d97b72a8bf967e8eea2e00032ebd6d5d

**Comment by purpl3F0x** [comment]
Should be fixed on 1.2.1. Plz let me know
