### ISSUE TITLE
Doesn't seem to work on macOS properly 

### ISSUE THREAD

**Issue by shikhir-arora** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#2]
I am able to build this fine and run it, and it connects fine, but there doesn't seem to have any data sent from Tidal. The socket connection is made, but the data is always sent with `null` - it does work on Windows, however, so I assume this is something with Tidal's macOS application but I may be wrong. 

Here's some relevant information: 

<img width="1033" alt="Screen Shot 2019-09-17 at 11 58 22 AM" src="https://user-images.githubusercontent.com/8797918/65059269-b1c49f00-d943-11e9-9410-bf1e1c96bee7.png">

![Screen Shot 2019-09-17 at 11 59 29 AM](https://user-images.githubusercontent.com/8797918/65059272-b5f0bc80-d943-11e9-8165-057b684ed283.png)

**Comment by purpl3F0x** [comment]
I don't have/use mac so I'm not able to provide to much help.
the app basically searches for the name of the tidal window. I don't know if an update have broken this feature but i doubt. 
this I would do is to see is the tidal window gets the artist - song as title.
Also try to run the app in debug mode to print the queries it makes to tidal api etc...
Let my know

**Comment by shikhir-arora** [comment]
Running it in debug mode shows that there's no bundle ID; I am running macOS Catalina beta, and apps have to be notarized now. I have a developer account so I'll sign it and see from there. Appreciate it!

**Comment by purpl3F0x** [comment]
Unfortunately vmware is broken on my machine and I can't test this. But with Mojave it seemed to work fine. Also you seem to be more experienced with macos programming (anything > 0), so I assume you have better chances finding what is wrong 😅.

**Comment by purpl3F0x** [comment]
@shikhir-arora Did you managed to fix it ?

**Comment by purpl3F0x** [comment]
closing since got no response, and might not have been an issue
