### ISSUE TITLE
Windows 10 - Entry point not found

### ISSUE THREAD

**Issue by jettagaviation** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#23]
Hi!

I'm having the following issue when trying to open tidal-rpc.exe. I do not have this problem on v1.1.1.

![image](https://user-images.githubusercontent.com/47341910/80629110-bf3d1e00-8a28-11ea-831d-ff036f1c85d3.png)

**Comment by PaulBGD** [comment]
So for windows `discord_game_sdk.dll` from the x86 or x86_64 folder needs to be included, as we can't statically link it.

@jettagaviation if you want a fix, download this to your Release folder: https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/blob/master/discord-game-sdk/lib/x86_64/discord_game_sdk.dll

**Comment by brunofgmag** [comment]
Hi!

I already have it, it is included in v1.2

**Comment by PaulBGD** [comment]
On the release page it doesn't look like it's actually included in the zip, you're sure it's in the release folder?

**Comment by brunofgmag** [comment]
![image](https://user-images.githubusercontent.com/19572425/80849452-8e5a1600-8bed-11ea-8516-feca3fb9947c.png)

**Comment by purpl3F0x** [comment]
Yeah I updated the release and j forgot to include it. But it seems there are still problems. Idk why.

**Comment by purpl3F0x** [comment]
Should be fixed on 1.2.1. Plz let me know

**Comment by brunofgmag** [comment]
At first, it gave me this message:

![image](https://user-images.githubusercontent.com/19572425/81932690-88d3d700-95c2-11ea-8830-6fe139aada8b.png)

But it was because my discord was not open. This version is working fine here.

Thanks!
