### ISSUE TITLE
[Windows 10] The application was unable to start correctly (0xc000007b

### ISSUE THREAD

**Issue by Konack** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#25]
OS: Windows 10 1909
Program Version: 1.2
Error: Application popup: tidal-rpc.exe - Application Error : The application was unable to start correctly (0xc000007b). Click OK to close the application. 

Steps to reproduce: Extract Release folder from tidal-rpc-win_x86-64.zip. Run tidal-rpc.exe and see error.

**Comment by purpl3F0x** [comment]
Please read the existing issues similar to #18
