### ISSUE TITLE
Won't run on Windows 10

### ISSUE THREAD

**Issue by k3lt** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#26]
Fully updated Windows 10 Pro x64, error says the application was not launched correctly, click ok to terminate it.

![1](https://user-images.githubusercontent.com/22222328/80702636-b0ff0880-8ae1-11ea-87c8-00c59ca2d2bd.png)

**Comment by purpl3F0x** [comment]
Similar to #18
