### ISSUE TITLE
How do I make the files into an exe?

### ISSUE THREAD

**Issue by Mewtzie** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#27]
Yeah, I'm sorry since I know this is usually for issues but I have nowhere to comment or ask queestions (at least I think). I downloaded Visual Studio Community to see if I could do it and looked around online to see if there's anything that can point me to the information. I simply just haven't got the slightest idea on how to make the folder/zip into an application. I really like the look of the rich presence and I'd be seriously happy to get it up and running.

**Comment by purpl3F0x** [comment]
Here you can download prebuild binaries https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/releases/tag/v.1.2.1
