### ISSUE TITLE
[Windows 10] Disable does not work

### ISSUE THREAD

**Issue by twhitson** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#28]
### Steps to reproduce
- Right click Discord Tidal RPC icon in tray
- Disable

### Actual behavior
Discord still says "Playing TIDAL"

### Expected behavior
Discord RPC should go away

**Comment by purpl3F0x** [comment]
Caused by the same as #29 
So closing to report on one issue
