### ISSUE TITLE
Master info doesn't work.

### ISSUE THREAD

**Issue by LynKoZ** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#30]
Hello, when i'm listening to master music, i can't see "master " on my profil.
![image](https://user-images.githubusercontent.com/54003578/83984075-76378e00-a933-11ea-93df-196747b89b1c.png) 

![image](https://user-images.githubusercontent.com/54003578/83984094-88b1c780-a933-11ea-88f2-c02b05b384db.png)
![image](https://user-images.githubusercontent.com/54003578/83984101-8fd8d580-a933-11ea-8dc8-291f07434a83.png)

**Comment by purpl3F0x** [comment]
Similar to #16 , see that thread for answer.
Thanks for reporting it tho either way.

Closing.

**Comment by LynKoZ** [comment]
Can you make " Listening to TIDAL " or no? ^^'

**Comment by purpl3F0x** [comment]
Nope sorry. I'm limited by the discord api

**Comment by LynKoZ** [comment]
Update ?

**Comment by purpl3F0x** [comment]
Nothing new, the discord api tho let's you put the type of activity although they haven't intergrated it yet for some reason. The app is ready for that then. So if they decided to fix it it won't need any update from out side

**Comment by LynKoZ** [comment]
Ow, there is a misunderstanding !
I talk about " Master info doesn't work "  😎

**Comment by purpl3F0x** [comment]
Oh 😳
Not really it's pretty much hit or miss. Although this track in my search comes first, so I will take a small look at it.

**Comment by LynKoZ** [comment]
Kk, i will be sad :(

**Comment by LynKoZ** [comment]
Re! 
Any update ?

**Comment by purpl3F0x** [comment]
Does it work with an earlier version, maybe ? If you could try 1.1 on a couple of songs...

**Comment by LynKoZ** [comment]
![image](https://user-images.githubusercontent.com/54003578/87864510-821e6300-c969-11ea-87c2-546f560a6b58.png)
Hello. Doesnt alway work

**Comment by purpl3F0x** [comment]
"doesn't always work" is expected behavior. The rpc doesn't know if you play an mqa track. It guesses based on the search result.

**Comment by LynKoZ** [comment]
So, there is a way to display this?

**Comment by LynKoZ** [comment]
＼（〇_ｏ）／

**Comment by purpl3F0x** [comment]
![image](https://user-images.githubusercontent.com/16735391/88787252-4327b300-d19c-11ea-85ec-b0f4ef388b7c.png)

**Comment by LynKoZ** [comment]
lmao, calm down bro. I saw but nothing work. I listened like 500 songs master and nothing.

**Comment by ririxidev** [comment]
@purpl3F0x, technically you could find Master quality in search results and just return it right away, like I do in my implementation in TypeScript: https://github.com/sleequid/tidalRPC/blob/main/src/managers/tidalManager.ts#L64. Maybe it will help you 😃
