### ISSUE TITLE
Download Latest doesn't work

### ISSUE THREAD

**Issue by LynKoZ** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#31]
Hello, we can't use the button " download latest " on ur github ^^'
![image](https://user-images.githubusercontent.com/54003578/84552234-6099de00-ad10-11ea-8547-67b6d6d8b57f.png)

**Comment by purpl3F0x** [comment]
https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/releases
