### ISSUE TITLE
Name too long

### ISSUE THREAD

**Issue by brian6932** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#33]
"Tidal - High Fidelity Music Streaming" is extremely long, why not just Tidal? If not a direct change at least making the program name customizable would be pretty nice.

**Comment by LynKoZ** [comment]
+1.
Maybe remove 
High Fidelity Music

**Comment by purpl3F0x** [comment]
okay then ;)

**Comment by brian6932** [comment]
Yea it worked, looks good 👍

**Comment by LynKoZ** [comment]
Love u so much <3
