### ISSUE TITLE
No more master identitifcation?

### ISSUE THREAD

**Issue by NocFA** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#34]
Hello,

So, recently I'm assuming since a few Tidal updates ago, it no longer says I'm playing master quality tracks when doing so with the separate orange colour, on top of this, it's now always showing I'm playing Tidal even when Tidal isn't running just like the other open issue.
I tried going back to previous versions and the master detection has the same issue, but, it stops pushing the status upon tidal closing, so, Tidal has obviously broken the MQA detection somehow.

**Comment by purpl3F0x** [comment]
It doesn't seem that they changed something in the api

![image](https://user-images.githubusercontent.com/16735391/85312400-756c3380-b4bf-11ea-8fa5-98e6a8ebbcbd.png)

**Comment by NocFA** [comment]
Apologies for the duplicate ticket, I didn't realize I actually reported this.
The issue is definitely still present, let me just copy and paste what I said in the recently opened duplicate:

Hello again!

I'm not too sure how long it's been since the feature has no longer worked, but, I noticed around the time the status changed from "Tidal - High Fidelity Music Streaming" to just "TIDAL"
I've tested with various songs, it'll never detect MQA.

Additionally, I remember there being some sort of text when you hover over the logo, IIRC it was the album or something else, this no longer has a function.

Anything I can provide, ask away,

OS: Windows 10 version 2004 build 19041.329
Tidal Build: 2.18.4.234

I'm thinking this may be an OS build issue if you're certain nothing has changed, as, 2004 is relatively new, although, it is live and being circulated to devices currently.

**Comment by purpl3F0x** [comment]
Does using an older version has the same issue?

**Comment by NocFA** [comment]
I might be able to test this, give me 48 hours.

**Comment by purpl3F0x** [comment]
Okay, 

It's 47h now 🕵️🕵️🙄

**Comment by NocFA** [comment]
Howdy!
I've tested on a system running Windows 10 1809, what I found was the master identification still did not work, along with this, elapsed time didn't track at all, it stuck at 0:00, this was using the latest v1.2 build

**Comment by rootblack45** [comment]
@NocFA @purpl3F0x They changed the authorization method from using x-tidal-token to authorization...I think they just change this because this morning my TIDAL account logged out again

**Comment by purpl3F0x** [comment]
that's good practice for security reasons. It doesn't have to do with the token.
But I will take a look at it, when I have time and feel like to :P

**Comment by purpl3F0x** [comment]
Yeah it seems that's an issue. I have found the new token
