### ISSUE TITLE
Change "Playing a game" to "Listening to"

### ISSUE THREAD

**Issue by Epacik** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#35]
In the new version of Discord integration API called "Discord Game SDK" you can change a "Playing" text to "Streaming", "Listening" or some custom one.

More info here:
[https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum](https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum)

**Comment by purpl3F0x** [comment]
Yes you can. But it's not working

**Comment by ciros88** [comment]
currently not possible according to: https://github.com/discord/discord-api-docs/issues/1002
