### ISSUE TITLE
Windows 10 - Data error: opengl32sw.dll, Headers Error: platforms\qwindows.dll

### ISSUE THREAD

**Issue by guy-dude** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#38]
**OS**: Windows 10
**Version**: Latest (1.2.1)

Received 2 errors (in title) when extracting the latest release (1.2.1).  Copying `platforms\qwindows.dll` from version 1.2 is working.

**Comment by purpl3F0x** [comment]
Did you try redownloading the zip ? It doesn't seem to be corrupted
