### ISSUE TITLE
mac m1 cpu

### ISSUE THREAD

**Issue by seegong** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#41]
it work in apple m1 chip?

**Comment by purpl3F0x** [comment]
Probably with Rosetta.
Haven't looked if discord library has m1 binaries.

**Comment by seegong** [comment]
ok...

**Comment by seegong** [comment]
hmmmmm it's not work in m1 chip 
this txt fill is error code !!


[message (1).txt](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/files/5821892/message.1.txt)

**Comment by purpl3F0x** [comment]
It seems it doesn't find Qt. I don't what's the problem here and if you can install an x86 version of Qt

**Comment by purpl3F0x** [comment]
probably fixed on 1.3. Feel Free to open topic again
