### ISSUE TITLE
Changing the rp icon in discord.

### ISSUE THREAD

**Issue by 3arknii** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#42]
I was wondering if it is possible to change the icon near the currently playing song to your own preferences?
![Screenshot 2021-02-02 110437](https://user-images.githubusercontent.com/78408288/106570080-77fb3500-6546-11eb-9f02-0e7c3548d523.png)

**Comment by 3arknii** [comment]
I'm not that good in programming though so if u could change it to this icon it would be more than appreciated.![image](https://user-images.githubusercontent.com/78408288/106574609-2b1a5d00-654c-11eb-846d-b13a98cf6a5c.png)

**Comment by purpl3F0x** [comment]
Can't, not good at programming either

**Comment by 3arknii** [comment]
No i mean in ur rp can u change the icon?
