### ISSUE TITLE
using this on macOS Big Sur

### ISSUE THREAD

**Issue by goreghost8** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#46]
Hi, are there any guides for noobies to make this work on macOS?

**Comment by goreghost8** [comment]
im sorry for this post, I didn't saw that

**Comment by goreghost8** [comment]
I just saw that there are osx versions available but it seems like it's not compatible for Big Sur, any fixes for that?

**Comment by purpl3F0x** [comment]
Tbh I don't even know how to build it on osx. 
Will give a try the afternoon

**Comment by goreghost8** [comment]
okay, thank you!

**Comment by RobyRew** [comment]
> Tbh I don't even know how to build it on osx.
> Will give a try the afternoon

If you need help with something im here 🙂

**Comment by purpl3F0x** [comment]
> > Tbh I don't even know how to build it on osx.
> > Will give a try the afternoon
> 
> If you need help with something im here 🙂

If you can built it with qt and discord libs packed 😅

**Comment by purpl3F0x** [comment]
probably fixed on 1.3. Feel Free to open topic again
