### ISSUE TITLE
Play time wrong between Tidal and Discord

### ISSUE THREAD

**Issue by solarisfire** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#47]
This is super apparent if you're halfway through a song and stop Tidal-Discord RPC from running and then start it again.

But even when you let Tidal play normally both times are slightly out of sync.

Is it possible to get Tidal-Discord RPC to query the Tidal API for the current playtime more frequently and update accordingly?

**Comment by purpl3F0x** [comment]
Yes, cause play time is guessed there no way around that. 
It works pretty well tho, the issue you described is for only on song, if you open rpc during playback

**Comment by solarisfire** [comment]
Oh wow, the Tidal API doesn't report current playtime? That's pretty frustrating...

**Comment by purpl3F0x** [comment]
There is no tidal API to use for it. I just parse the running processes and get the song from the window title :P
