### ISSUE TITLE
Playback Time

### ISSUE THREAD

**Issue by DarkKnight226YT** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#49]
If you start up the RPC in the middle of a song, the time will not show the same time elapsed as the song actually is (ex: the song is 2:15 on TIDAL but it shows 0:56 on Discord). This also leads me to wonder if there's a way to have it show the time remaining in a song instead of how much of the song has elapsed. I hope I'm not saying too much and you understand what I'm trying to imply here.

**Comment by purpl3F0x** [comment]
See #47
