### ISSUE TITLE
Looking for someone to build Mac binaries

### ISSUE THREAD

**Issue by purpl3F0x** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#5]
I'm looking for someone that has a Mac and might be able to compile the Mac binaries, because me osx programming knowledge is zero to none.

**Comment by purpl3F0x** [comment]
Compiled a release on a VM running Sierra. It seems to work to me... 🤔

https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/releases/tag/v.1.1

**Comment by shikhir-arora** [comment]
❤️ Can confirm this works on macOS Catalina (10.15.1 Beta (19B77a)) 

Cheers 👍

**Comment by purpl3F0x** [comment]
Closing for now, if anyone has an issue specific to mac post here.

**Comment by CSR84210** [comment]
Can someone please help me on how to build this on mac I have zero knowledge. Thank you.

**Comment by purpl3F0x** [comment]
@CSR84210 I have made pre-build binaries available. They should work according to others.

**Comment by wl03355609** [comment]
idk how to use that pre-build one since it seems it's not a zip, app or pkg
Can you help me out?

**Comment by purpl3F0x** [comment]
@wl03355609 download it. 
- open your terminal go to Downloads (`cd Downloads`). 
- mark it as executable `chmod +x tidal-rpc_macos_sierra.dms`
- run it `./tidal-rpc_macos_sierra`
