### ISSUE TITLE
Mac OS workaround for missing Discord dylib

### ISSUE THREAD

**Issue by uwueviee** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#50]
A workaround to get tidal-rpc to launch on Mac OS is to specify the directory that `discord_game_sdk.dylib` is located in via `DYLD_FALLBACK_LIBRARY_PATH` in the Terminal.

For example, I was able to successfully launch it using `env DYLD_FALLBACK_LIBRARY_PATH=./discord-game-sdk/lib/x86_64/ ./tidal-rpc.app/Contents/MacOS/tidal-rpc ` after building it myself.

CMake/Make doesn't seem to statically link the Discord library and as a result the app tries to look for it in `@rpath`  (which using `otool -l` doesn't seem to actually be present) , `DYLD_FALLBACK_LIBRARY_PATH` will cause to app the look in the specified directory after the `@rpath` lookup fails, setting it to the `lib/x86_64` folder in Discord's Game SDK download will allow Mac OS to find the missing library.

Basically (Remember to replace folder names where applicable):
1. Download Discord's Game SDK and extract it into a folder
2. Download this repo's code and extract it into a folder
3. Install QT5 & CMake via [Homebrew](https://brew.sh/) with `brew install qt5 cmake`
4. Run `brew info qt5` to find the location of Qt5 (Look under the Qt URL)
5. Enter the extracted repo's folder and do `mkdir build && cd build && cp -r ../discord-game-sdk ./ && env Qt5Widgets_DIR=<location of qt5> cmake .. && make`
(After this, you've built the app and you can move it into the Applications folder if you'd like)
6. Enter `env DYLD_FALLBACK_LIBRARY_PATH=<folder where discord sdk is located>/discord-game-sdk/lib/x86_64/ <folder where tidal-rpc is located>/tidal-rpc.app/Contents/MacOS/tidal-rpc` and it should start up.

You'll only need to do step 6 every time you want to start it up.

**Comment by purpl3F0x** [comment]
I guess there could be a script that launches the app ?
Or finally found where the discord lib should be put I to 😅

**Comment by purpl3F0x** [comment]
probably fixed on 1.3. Feel Free to open topic again
