### ISSUE TITLE
Sorry but I cant direct msg you on here

### ISSUE THREAD

**Issue by HaydenCappadona** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#52]
First, Thank you for this Rich Presence. It has been great.
Idk if you know this but Tidal MQA is handled much better through Audirvana. You can hear the difference.
Uhh, if you also find the same, would awesome if you made an Audirvana Discord Rich presence...
Cheers Regardless,
Hayden.

**Comment by purpl3F0x** [comment]
No it doesn't, It is just a bitstream.
