### ISSUE TITLE
Big Sur Support

### ISSUE THREAD

**Issue by ItsNotOp** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#55]
Will this be ported for Big Sur? If not, how do you build it on Big Sur?

**Comment by purpl3F0x** [comment]
There same issues (& paco of knowledge) about the Mac binary. 
But in order to built it you need the qt library and then it's straight forward with cmake.

Also I don't think there is an issue with big sur, if the app doesn't work check #50

**Comment by ItsNotOp** [comment]
I tried the OSX rpc file from an earlier version (that sadly wasn't compatible with Big Sur) because either I'm blind (which I probably am) or there is no MacOS rpc application for the latest version

**Comment by purpl3F0x** [comment]
probably fixed on 1.3. Feel Free to open topic again
