### ISSUE TITLE
TIDAL Master golden icon isn't displayed in Discord

### ISSUE THREAD

**Issue by lRoberth** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#57]
Just as the title says. It instead uses the normal icon.
![image](https://user-images.githubusercontent.com/15135969/126916449-69b42507-6f5c-4fd6-9235-2e9de68503f3.png)
![image](https://puu.sh/HZ7nQ/ca17d2f1bf.png)

**Comment by Korigg** [comment]
Up

**Comment by purpl3F0x** [comment]
#30
