### ISSUE TITLE
Reset time elapsed when song is put on repeat (feature request)

### ISSUE THREAD

**Issue by sofiazulkifli99** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#58]
The time elapsed for when a song put on repeat is continuous. Would love to have this feature add if possible. 
![Image 4](https://user-images.githubusercontent.com/77136144/129474847-cc300ec5-793c-4d6b-a32b-a2be9e98a3c4.png)
![Image 5](https://user-images.githubusercontent.com/77136144/129474851-f3ed688e-6230-449c-aa3c-3e473173b225.png)

**Comment by purpl3F0x** [comment]
How would you know that the song is on repeat and not someone is scrolling back and forth for example ?

**Comment by sofiazulkifli99** [comment]
Well, how do i know when someone put a song on repeat is like I've shown on the screenshot. I clicked repeat a song. I requested this because i also use the itunes rich presence on discord and it has the feature that i requested. But if it's not possible for tidal, it's okay. I'm just asking.

**Comment by purpl3F0x** [comment]
I took quick look at some of the rpc's for itunes. It seems itunes has a genuine  API to get those info from the it. 
As explained this app is more like a hack
