### ISSUE TITLE
New update v1.3.0.62 doesn't work on Windows 10/11

### ISSUE THREAD

**Issue by ramkpari** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#59]
**System Configuration**

- Discord v98643 
- Tidal windows client v2.28.0.238 
- Win 11 (22000.194)

The old version (v1.2.1) used to work with the current build before updating to v 1.2. With v1.3.0.62, the RPC client seems to be stuck on the waiting status

Update: 
Reverting back to v1.2.1 still works!

**Comment by purpl3F0x** [comment]
Sorry, I'm not going to debug the app on not even beta OS versions.

I have the same Discord & Tidal versions and works as expected. So it probably comes down to windows 11 except future proves it wrong

**Comment by ramkpari** [comment]
Fair enough.  Just for information, the 22000.194 version is the release version that will be pushed to the general public on Oct 5.

**Comment by Moresteck** [comment]
The issue still happens on the stable release of Windows 11. Please consider fixing it

**Comment by purpl3F0x** [comment]
Yes seems to be an issue will try to find time to fix it. Will give a shot next weekend

**Comment by malcrypted** [comment]
Just wanted to add that this version also doesn't work for me on Windows 10 Pro 21H1 (build 19043.1288, feature experience pack 120.2212.3920.0), I had previous version which worked but I am not sure which one it was.

**Comment by purpl3F0x** [comment]
It seems to be a qt problem. I made a build with wt version 6.2.0 it seems to work on the VM.
If someone can confirm it's working, I will push the new build 

https://www.dropbox.com/s/wbd733o502r7v32/cmake-build-release.zip?dl=0

**Comment by purpl3F0x** [comment]
I probably zipped something wrong try this one:

[Uploading tidal-rpc-qt6.zip…]()

**Comment by purpl3F0x** [comment]
I don't think there needs to be a specific order. But I would open the rpc last I guess.

Don't think the dll missing is the issue. Seems I have to take another look at it

**Comment by Ravelair** [comment]
Thanks for your work. Id help more but I never used Qt before nor did I ever code in anything but python.

**Comment by Minecon724** [comment]
i think you should update the title, this also happens on windows 10

**Comment by purpl3F0x** [comment]
Does it work for anyone if he install openssl ?? 

https://slproweb.com/download/Win64OpenSSL_Light-3_0_0.exe

**Comment by Minecon724** [comment]
> 
> 
> Does it work for anyone if he install openssl ??
> 
> [slproweb.com/download/Win64OpenSSL_Light-3_0_0.exe](https://slproweb.com/download/Win64OpenSSL_Light-3_0_0.exe)

nope

**Comment by purpl3F0x** [comment]
Well I will just remove the auto update thingy for now then.

**Comment by SleepDaemon** [comment]
Hi, in the latest version there are some folders missing mainly iconengines
![image](https://user-images.githubusercontent.com/88533953/140064316-4291155d-b7f5-4ffa-a32a-5b8fcf2edb23.png)
![image](https://user-images.githubusercontent.com/88533953/140064365-745c4e66-c79f-4e07-8285-067b63cb4f2b.png)

TOP: Fix 1.2
Bottom: v1.3

**Comment by purpl3F0x** [comment]
Where is that relevant ? Does it cause the issue ?

**Comment by SleepDaemon** [comment]
Idk but my friend said it seems the older one works and I’m running the older version as well and it’s working fine. Just master detection not working.

**Comment by purpl3F0x** [comment]
One last try, if this one works... Else i don't know. I will drop the auto update, cause I don't have infinite time.

[tidal-rpc_test.zip](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/files/7469016/tidal-rpc_test.zip)

**Comment by SleepDaemon** [comment]
> One last try, if this one works... Else i don't know. I will drop the auto update, cause I don't have infinite time.
> 
> [tidal-rpc_test.zip](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/files/7469016/tidal-rpc_test.zip)

yep, the older works fine. Just master detection is broke.

**Comment by purpl3F0x** [comment]
> > One last try, if this one works... Else i don't know. I will drop the auto update, cause I don't have infinite time.
> > [tidal-rpc_test.zip](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/files/7469016/tidal-rpc_test.zip)
> 
> yep, the older works fine. Just master detection is broke.

Does the zip I dropped work ?

**Comment by Minecon724** [comment]
> 
> 
> > > One last try, if this one works... Else i don't know. I will drop the auto update, cause I don't have infinite time.
> > > [tidal-rpc_test.zip](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/files/7469016/tidal-rpc_test.zip)
> > 
> > 
> > yep, the older works fine. Just master detection is broke.
> 
> Does the zip I dropped work ?

for me it does

**Comment by purpl3F0x** [comment]
AHH, yes!

**Comment by SleepDaemon** [comment]
> > > One last try, if this one works... Else i don't know. I will drop the auto update, cause I don't have infinite time.
> > > [tidal-rpc_test.zip](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/files/7469016/tidal-rpc_test.zip)
> > 
> > 
> > yep, the older works fine. Just master detection is broke.
> 
> Does the zip I dropped work ?

that i didnt check cause its late for me

**Comment by SleepDaemon** [comment]
pog

**Comment by SleepDaemon** [comment]
> AHH, yes! We were missing some dlls.
> 
> I will post the updated zip tomorrow, if anyone wants to get it working manually, you need to install openssl 1.1.1l

aight ill let my friend know

**Comment by agkingrey** [comment]
Hey, nice! Congrats! Excited to try this tomorrow

**Comment by ramkpari** [comment]
Running the test version without OpenSSL and test version seems to pick up the data from TIDAL as expected!

**Comment by purpl3F0x** [comment]
Good to hear that. 
I'm wondering does it still work if you delete the openssl and libcrypto dlls ?

**Comment by Acrivec** [comment]
Is the problem back?
Currently 'waiting' and nothing happens.
Microsoft Windows [Version 10.0.19043.1566]
