### ISSUE TITLE
Suggestion: "Timeout" on extended pauses

### ISSUE THREAD

**Issue by shikhir-arora** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#6]
Hey there - 

Thanks for making this - really useful to us Tidal users! 🙂 

I have a suggestion - it seems that after a period of a few minutes of pausing a playing track, then resuming, the app reports that it cannot get the time from the API and shows it as `00:00` (which makes sense in the current design, assuming no cache). Do you think it would be better if it just defaulted to the standard window after a few defined minutes of idle pausing? Then, on replay, it can query the API again.

**Comment by purpl3F0x** [comment]
What do you mean ?
If you pause a song, then the app checks every second to see if you have resumed, it also increases the remaining time by 1sec. So on resume the remaining time is somewhat accurate, it's as accurate as it gets TBH, without checking more frequently.
At least that is the way it supposed to work 😅.
Tho I'm not sure if I answer your question, let me know. 👀

**Comment by shikhir-arora** [comment]
Hey, it does work like that if you just pause a song and play it again (within a few minutes, otherwise it gets that error that I stated "cannot get time from API" and goes to `00:00`. I guess my suggestion is aimed towards if you go to another position in the track and unpause, then it is not accurate. Sorry about that point of confusion!

**Comment by purpl3F0x** [comment]
So i played a track about half way (5 minutes long) and stopped it for about 10 minutes, and timing was good... Tried some combination, but i couldn't reproduce it.

P.S. if you scroll thru the track, obviously the correct time remaining brakes, but that should cause any hard errors... 

Let me know
