### ISSUE TITLE
Seems 1.3 isn't working

### ISSUE THREAD

**Issue by MertUnverdi** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#60]
i tried 1.3 but isn't linking
1.2 works perfectly tysm <3

**Comment by MertUnverdi** [comment]
already reported sorry

**Comment by purpl3F0x** [comment]
Hello, What is the problem ? What OS are you running ?

**Comment by MertUnverdi** [comment]
Windows 11, wasn't links to Tidal app

**Comment by purpl3F0x** [comment]
Yeah sorry no support for windows 11 atm
