### ISSUE TITLE
Time counter contiunes count while paused

### ISSUE THREAD

**Issue by MertUnverdi** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#61]
u should stop timer until not resuming 👍🏻

**Comment by purpl3F0x** [comment]
What OS are you using I don't see that issue ? Does it happen all the time or happened once ? Maybe It was discord fault

**Comment by MertUnverdi** [comment]
its always happens on win 10 and win 11
I don't think discord's fault prob u're forgot stopping timer or smthing idk

**Comment by purpl3F0x** [comment]
It works fine for me on windows 10

**Comment by MertUnverdi** [comment]
![image](https://user-images.githubusercontent.com/69310169/135837393-ff724325-a0f5-4624-ab19-8a31016baf0a.png)
i've stopped and resume again 
![image](https://user-images.githubusercontent.com/69310169/135837442-2828acdd-377c-4eb9-abb0-bfea5dc6265d.png)

**Comment by MertUnverdi** [comment]
it always happens, may about v1.2 ?

**Comment by purpl3F0x** [comment]
Ah I see the problem. It doesn't find the song online. So the app doesn't know the song runtime and doesn't use a "Remaining" counter. Probably if you try a more popular/normal song. 
Report back it might also be the token I use, in that case, it will need a fix.

**Comment by MertUnverdi** [comment]
![image](https://user-images.githubusercontent.com/69310169/135839335-60db63d4-906f-4fe4-99b9-8e36477ff665.png)
![image](https://user-images.githubusercontent.com/69310169/135839464-4cba1d1b-35e0-4dbf-928f-68132a0f21f4.png)
seems same for most popular songs

**Comment by kulaid** [comment]
Still happens for me Windows 11

**Comment by K-Schaeffer** [comment]
Working windows 11 (latest release v.1.3.0.91)
