### ISSUE TITLE
Not Working/Status: Waiting

### ISSUE THREAD

**Issue by ThePescatarian** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#63]
I followed the  instructions and enabled game activity on discord. I even disabled and re-enabled. 
![unknown](https://user-images.githubusercontent.com/92696208/137647691-a33ef11b-5ef7-462b-8d3c-bc26916709cd.png)

**Comment by ramkpari** [comment]
Hey,
This issue is a duplicate of #59 and is currently being worked on
