### ISSUE TITLE
App no longer works with Discord update

### ISSUE THREAD

**Issue by SolderOtter** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#64]
My environment:
Stable 102737 (a3b6a47)
BetterDiscord 1.2.3
Host 1.0.9003 Windows 10 64-Bit (10.0.19043)

Honestly not sure what else to say than it stopped working when Discord updated, and removing the base folder and replacing it with a fresh copy of the latest release didn't fix the issue.

**Comment by purpl3F0x** [comment]
Does the rpc on the status icon shows you are playing something ? Or it says "waiting" ?

**Comment by Nichevo82** [comment]
> Does the rpc on the status icon shows you are playing something ? Or it says "waiting" ?

It's not working for me either. Tried with Discord 103016 (54edf1f) and Canary. Using Tidal 2.28.0.238. The status in the taskbar says "Running", and "Status: waiting" is greyed out. Doesn't say I'm playing something.

**Comment by TypicalModMaker** [comment]
> > Does the rpc on the status icon shows you are playing something ? Or it says "waiting" ?
> 
> It's not working for me either. Tried with Discord 103016 (54edf1f) and Canary. Using Tidal 2.28.0.238. The status in the taskbar says "Running", and "Status: waiting" is greyed out. Doesn't say I'm playing something.

Works fine for me, BetterDiscord v1.2.3, Discord 103016 too
![image](https://user-images.githubusercontent.com/52781429/139668705-01f069dd-0136-447c-9c1e-08e290ff837b.png)

**Comment by purpl3F0x** [comment]
#59
