### ISSUE TITLE
Won't detect my Tidal at all

### ISSUE THREAD

**Issue by ElFatFat** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#65]
So I tried to use the latest version and the one before, but both don't work in my case. The status stays "Inactive". I've no idea if I can provide logs, so tell me if I need to and how to. 
Thanks !

**Comment by VaiJack8** [comment]
Hi, I have the same issue except my status stays "waiting". Hope this can be fixed.

**Comment by purpl3F0x** [comment]
Does this work ?

https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/files/7469016/tidal-rpc_test.zip

**Comment by VaiJack8** [comment]
> Does this work ?
> 
> https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/files/7469016/tidal-rpc_test.zip

Yes it does. Thanks.

**Comment by purpl3F0x** [comment]
Yes I just saw there is a mess up  in the release again

see #59
