### ISSUE TITLE
app crashes when it launches discord also (also Better Discord)

### ISSUE THREAD

**Issue by MrOverlord12** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#66]
So it got updates yesterday, because people seemed to have issues. I have the same issue even with the latest update. I tried the test version that was made but that doesnt work either. Interestingly enough it starts, opens my discord into the old games tab (from back when discord tried making their own DRM like steam) and then it just closes. Running on Windows 10 Pro 21H1 and latest Stable client on discord with Better Discord installed on it.

**Comment by purpl3F0x** [comment]
You didn't provide much info, BUT
Your discord start-up is as expected, the discord-game-sdk launches the app if it's not running. 
But what I noticed with some experimentation is that when you do that for some reason the rich-presence app exits (possibly crashes didn't debug it). 
If tho you relaunch the rpc it seems to work just fine. At least on me, do you experience the same ?

**Comment by MrOverlord12** [comment]
It sadly doesnt. Crashes again and again. Keeps sending my Discord to the old games page. Is there any more info youd like id be happy to tell you since you said i provided too little.

**Comment by purpl3F0x** [comment]
Hmm I see, I don't know how I can debug that.
I will try to solve the problem I am getting. Maybe it fixes your issue also. I will take a look at it tomorrow.


You didn't have the same problem with the previous app version ?

**Comment by MrOverlord12** [comment]
Same issue with the latest and previous release. The older ones dont behave that way but throw me dll errors or just start but dont work at all.

**Comment by purpl3F0x** [comment]
Issue seems to be right here, That's on discod's fault not mine
https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/blob/98694999ab835baaca4a8fe1580c321eafbea433/main.cc#L195

**Comment by MrOverlord12** [comment]
Sad that discord is at fault. Wont be fixed in a while if ever probably then.

**Comment by MrOverlord12** [comment]
Ok so, it just doesnt work with Better Discord. Just launched normal discord and now it works. Apologies for causing a confusion. Seems like this isnt really an issue since it only affects Better Discord which is unofficial anyways. Still thanks a lot for taking time out of your Weekend to check whats up, really appreciate it!

**Comment by purpl3F0x** [comment]
Yeah there seems to be something going-on.
I might have a small fix for it. But since it doesn't work at all for Better Disc. that is out of the question.

**Comment by purpl3F0x** [comment]
This is probably a fix https://github.com/discord/discord-api-docs/issues/2046

**Comment by donnaken15** [comment]
> This is probably a fix [discord/discord-api-docs#2046](https://github.com/discord/discord-api-docs/issues/2046)

that solution doesn't work

the only way to get around this is to use LoadLibrary as the error is discarded and code gets to move along

i got rich presence working for a game mod and because this POS app's "SDK" is dynamically linked, it's causing people's game to get the error at DiscordCreate for the app not being on

another valid reason to hate Discord

**Comment by donnaken15** [comment]
Found a fix by using a debugger to see what DiscordCreate does in the event of not having the app open

It returns a EDiscordResult value (InternalError/4) in this case

WHERE WAS THIS MENTIONED IN THE DOCUMENTATION!!!!!! (only on Rust docs for some reason)

Yet, sample code doesn't specify this

**Comment by donnaken15** [comment]
NOW IT'S FLAT OUT NOT WORKING

I'M GETTING ERROR 4 EVEN FROM THE EXAMPLE PROGRAM

**Comment by donnaken15** [comment]
> it's causing people's game to get the error

**Comment by Ganeshaha** [comment]
Not sure if this is the same error, but this is my experience:
With Discord, Tidal, and trpc closed, when I launch tidal-rpc, Discord and trpc both launch.
After that, trpc seems to crash immediately but Discord launches fine.
Once Discord is launched, I am able to launch trpc without it crashing.

Having Tidal open or closed does not seem to affect this.
I think adding a 10 second wait/sleep loop or try/catch and having trpc run the check again instead of crashing would functionally fix the issue for 99% of users as Discord usually doesn't take longer than 10 seconds to load. 

I'll put a $10 bounty on the bug, if someone is able to fix it I will send them $10. (require proof of course.)

**Comment by donnaken15** [comment]
for some reason the error also is partially fixed when Discord is reinstalled
this app makes no sense and is the most pain inducing thing ever

**Comment by purpl3F0x** [comment]
I pushed an update that seems to fix the issue. Appveyor build seems to have an issue, if anyone can build it his/her-self and confirm it's functional.

**Comment by Ganeshaha** [comment]
I don't know enough about these libraries to test it out. If anyone else is able to compile it and get it working I will be donating to this project,

**Comment by purpl3F0x** [comment]
https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/releases/tag/v.1.3.0.109

**Comment by Ganeshaha** [comment]
If future issues arise I probably won't mind sponsoring those as well.
