### ISSUE TITLE
Not working on macOS Monterey

### ISSUE THREAD

**Issue by LuckyFinger** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#70]
I have a Macbook Air (M1, 2020) running macOS Monterey (version 12.2.1)
First time I opened the .dmg file, it was asking me some weird things that made me think that this program is a virus. tidal-rpc.dmg asked if it could record my screen, which I found obscure and unnecessary. Of course, I pressed deny. I don't know if I would've had problems if I let it but I don't see why that would be the solution.

It is stuck on "Status: waiting for Tidal" when I had Tidal open the whole time, including Discord. I'm not sure if I should make tidal-rpc be detected by Discord, or if I should make it the Tidal application. I hope one of you guys could help me.

**Comment by purpl3F0x** [comment]
That permission is required to read the tidal window name that's how I get the song title. 
If you think my app is a virus just don't use it. Anyway, tho the source code is all here hundreds people have downloaded the app. And a few have checked it's code

**Comment by LuckyFinger** [comment]
Thank you, it works. However, master mode does not display on the status.

**Comment by purpl3F0x** [comment]
Master is a lucky shot. I will work on a slight modification when I have time. See similar pinned topics
