### ISSUE TITLE
Showing time elapsed instead of time left

### ISSUE THREAD

**Issue by RubizZ** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#74]
Currently, when reproducing something, it shows the time elapsed, and it should be time left of the song, doesnt make sense if you pause its still counting. Maybe it should be "Time elapsed: 1:23/4:56" where 1:23 is the time elapsed of the song, and 4:56 the duration of the song, or just time left of the song

**Comment by purpl3F0x** [comment]
Read the similar issues please.
