### ISSUE TITLE
Change Playing a game in the status to "listening to"

### ISSUE THREAD

**Issue by SDWaps** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#77]
eg: 
![image](https://user-images.githubusercontent.com/47910472/183889925-96010fc9-f6aa-46c1-83a6-bf58d5d30a6b.png)
![image](https://user-images.githubusercontent.com/47910472/183890201-342cd02b-4e30-4738-8c89-84362993509b.png)
(so sorry about image quality i used ms paint lol)

**Comment by obeeblue** [comment]
thisssss

**Comment by purpl3F0x** [comment]
#35
It's implemented see the code, discord hasn't bothered to implement it
