### ISSUE TITLE
Very annoying thing

### ISSUE THREAD

**Issue by obeeblue** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#78]
Hey! was curious if you could get the album covers to load ever? Another github user, by the name of Unickorn got it to work, but it's both a little buggy, and isn't as progressed as this one from what it seems.

**Comment by purpl3F0x** [comment]
Why you opened a separate issue ? It has been asked before. It's not supported by discord. Someone mentioned that now it's possible but did not provide any information on how and i don't find documentation for such a thing
#2
