### ISSUE TITLE
Album art not showing up

### ISSUE THREAD

**Issue by XiCynx** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#79]
Displays the Song and Artist and time left on song, but does not display the album art, it's just the Tidal icon.

![image](https://user-images.githubusercontent.com/20632191/187065707-406bb10a-61d6-4694-ace2-c26d90352264.png)

**Comment by purpl3F0x** [comment]
Who said it should! Look at the other opened issues, literally it's on front of your nose
