### ISSUE TITLE
Add a warning that discord may ban accounts because of album covers

### ISSUE THREAD

**Issue by LeoLTM** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#83]
On another project (discontinued!) providing Discord Rich Presence support for Tidal, someone suggested implementing the functionality to show album covers in the status, but another user mentioned that Discord bans people using accounts as a "bot", even though that is not the case here. It seems like showing album covers in your profile triggers some kind of bot detection. 

Maybe it would be a good idea to add a small warning to the readme so others can use this feature at their own risk.

EDIT: 

An option to toggle the usage of album covers in the RP status would be good as well, maybe in the right-click menu where you can `Exit` and `Enable/Disable` the RP.

**Comment by purpl3F0x** [comment]
Noy even sure what you mean

**Comment by LeoLTM** [comment]
Yeah I know that this is not a Discord bot but using the Rich Presence status of your Discord profile to show the currently playing song / album with the cover looks like someone is using a normal Discord account (not a Discord bot) to stream music on his Discord server, even though the account is not a bot at all. It just LOOKS like that and that might be enough for Discord to ban accounts, just saying.


here some links:
[Github, check the beginning of the readme](https://github.com/Unickorn/discordtidal)
[Reddit 1](https://www.reddit.com/r/discordapp/comments/695gqh/comment/dh403l6/?utm_source=share&utm_medium=web2x&context=3)
[Reddit 2](https://www.reddit.com/r/discordapp/comments/7qlgc3/comment/dsq0dp7/?utm_source=share&utm_medium=web2x&context=3)

**Comment by purpl3F0x** [comment]
Again: The app is using the **OFFICIAL** discord rich presence module provided by the **OFFICIAL** discord game sdk.

If you wanna know more about it here https://discord.com/developers/docs/game-sdk/sdk-starter-guide
