### ISSUE TITLE
It does not show exactly which song is playing at the moment.

### ISSUE THREAD

**Issue by RetroBeatFM** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#84]
Yes, the programme does what it promises, but in some cases it does not show the original songs, instead it shows another song with the same title. 

Example: when playing a "live" version, the program shows as if it is playing a studio version.

**Comment by purpl3F0x** [comment]
It's inevitable. Most of the times the reported song title if live albums for example is just the song title any (live at something) for example gets stripped.

**Comment by RetroBeatFM** [comment]
Yes, but clarifying the above points:
1. It happens with songs that clearly have "(Live)" in the title.
2. Not even the original cover of the song is shown. 
Unless this has to do with the region the album is available in, although I thought it depended on exactly what you were listening to.

**Comment by purpl3F0x** [comment]
@RetroBeatFM
1. If you notice Tidal removes the Live from title, same applies for classical that might include keys or something similar. 
For example:
![image](https://user-images.githubusercontent.com/16735391/213628512-d5f8457a-5e25-4b65-86f2-155cbc90e6ab.png)
![image](https://user-images.githubusercontent.com/16735391/213628601-ed5de262-0bd9-496e-a47d-6591dc3246d9.png)
2. I have thought that might be an issue and the app,gets the region you are in from windows/osx and tries to be compliant with what countrie you are probably listening form
