### ISSUE TITLE
Album cover stopped showing

### ISSUE THREAD

**Issue by lopes143** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#86]
Recently I posted about different album covers, but today my album cover stopped showing on Discord.

![image](https://user-images.githubusercontent.com/120063531/213929346-e257abf7-a2cc-4146-a35c-4e9eb58f7fd8.png)

I reinstalled everything and didn't solve.
I don't know if TIDAL or Discord released a new update that made this not work, but I leave my problem here.

**Comment by purpl3F0x** [comment]
I just tested it and works for me, maybe it's the song. I see that is indicates _decorridos_ which according to google translate means elapsed. When the app says elapsed and not remaining it usually means that it didn't find the song

**Comment by rodrigosplopes06** [comment]
Thanks for the quick response, its weird but I tried with other songs, even with the song I showed on last post and the results are the same. I don't know what caused this to happen, but I will keep finding. My pc is a completely mess, lots of trash and cache files...

**Comment by rodrigosplopes06** [comment]
**I FOUND THE SOLUTION**

I don't know how this came to my mind but when I organized my pc I put the _tidal-rpc.zip_ file from GitHub inside the dir I have tidal-rpc files.

And this coused the bug

So minutes ago I tried without the zip file and _it worked_ :)

**Comment by rodrigosplopes06** [comment]
So, after few days it happened aggain: stop showing again. I don't have the zip file anymore, I cleaned Discord and TIDAL cache, ran windows filesystem checkers and still have this problem. Also a friend of mine who has tidal-rpc too end having the same probem.

I tried everyhing but now I really don't know that's the problem

**Comment by ShuriZma** [comment]
@rodrigosplopes06 so instead of the album cover there is just no image at all? did you try checking the dev console?
you can open it using ctrl + shift + i 
if youve opened it you should check if there is an image linked or not. there is that small cursor symbol at the top left of the dev console if you click that you can afterwards click at the place where the album cover should be and then check if the <img> tag contains any url. (should look sth like src="somelink")
might be a cache problem or something.

**Comment by rodrigosplopes06** [comment]
This is the src="" text I found in <img> tag of the cover:

src="https://media.discordapp.net/external/ywdxXIXlL1fDpn-Je0qrREo-SYwTgu9PecdReMtQdkU/https/resources.tidal.com/images//1280x1280.jpg"

Idk if this helps, and I couldn't find if there is any personal information, so I leave it here.

**Comment by ShuriZma** [comment]
https://resources.tidal.com/images//1280x1280.jpg seems to be the image link being set by the rpc then. looks like it couldnt properly build the url or something?

**Comment by purpl3F0x** [comment]
Is this still an issue ?

**Comment by Pugchaamp** [comment]
I have the same problem, and the same results in element section. 
And it fixes only when ALL system traffic goes through VPN/Tunnel on my PC (link in img src become perfectly right and img shows). 

But in my situation I only need a few domains to go through proxy, including tidal.com ones to let Tidal work in my country. I think your app is somehow unable to access tidal recources.

So, is there any way to let your process to go through my system proxy settings? I use v2rayN app, and it lets me to add domain, ip or ip cidr to go through proxy.

P.S.: I tried to let discord go through proxy, but it didn`t help. Windows firewall is off.

**Comment by lopes143** [comment]
I think the problem is now solved, as we now know the issue.
