### ISSUE TITLE
Change the text order

### ISSUE THREAD

**Issue by JamesDAdams** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#89]
Hi, it's possible to change the text order from this : 
![image](https://user-images.githubusercontent.com/20860324/229345755-b180cd45-4bb2-42cf-b12d-8d7f0a8aec6b.png)

To this : 
![Sans titre](https://user-images.githubusercontent.com/20860324/229345874-5b91de9c-7337-4707-8947-410d726a7c6e.png)

**Comment by purpl3F0x** [comment]
Is this a question or suggestion ?

**Comment by JamesDAdams** [comment]
A suggestion :)

> Is this a question or suggestion ?

**Comment by purpl3F0x** [comment]
How can you put the application name on the bottom?
I don't see anything in the SDK docs...

**Comment by JamesDAdams** [comment]
> w can you

Paint ^^ it's for example

**Comment by purpl3F0x** [comment]
?
