### ISSUE TITLE
Tidal not showing up in Discord

### ISSUE THREAD

**Issue by Seolenn** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#91]
Hello, I tried multiple time to do as said in the tutorial but to no avail.
If someone have any idea how to solve it, it would be much appreciated.
[](url)
![Discord_Alzjo0QPnV](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/assets/60849762/1dc35658-1e76-4eac-84a4-d006c3691111)
![32HSzjPFFq](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/assets/60849762/8ef5d842-2905-4427-86e5-9877cafa2df2)

**Comment by purpl3F0x** [comment]
I think you don't need to do that any more?
Does your status get updated?  (Assuming you're "online")

**Comment by Seolenn** [comment]
I want to facepalm myself sooo hard, I was just focused on that particular part.
Thanks you bother answering such a dumb one lol.
Much thanks, Have a great day.
