### ISSUE TITLE
Hi-res icon not showing when playing master quality audio.

### ISSUE THREAD

**Issue by Ogwy** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#94]
![image](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/assets/89654233/dd027a31-c676-45eb-bb73-0f06a2c72112)
This is what its "supposed" to look like according to the example screenshots on this github page.

![image](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/assets/89654233/0bead631-eaf4-442b-8c90-6bf0bec0d786)
but it doesn't show the hi-res icon. Only when i hover over the album cover does it show playing hi-res audio. Was it changed at some point?

**Comment by purpl3F0x** [comment]
Hello, looking at the code I have removed it at some point.
Either way mqa being high-res audio is controversial and I'm addition the apo doesn't really know if it's master track or no.
