### ISSUE TITLE
RPC not showing up at all

### ISSUE THREAD

**Issue by Finrahel** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#95]
I have the Tidal-RPC launched and running with tidal and discord but it won't show up at all. I have a "Tidal-rpc" that might show up in activity where i choose one. I don't know if it shows up every time I still didn't test it. But i only have this :
![image](https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/assets/67865335/e207bcb3-cf25-4db5-84a5-de45fbc7ec9d)

**Comment by purpl3F0x** [comment]
At first, you shouldn't choose the program manually from settings, it be registered automatically on discord.

**Comment by Finrahel** [comment]
That's the problem, it doesn't appear... Like it's doing nothing...
Nevermind it's working now... What the hell I don't understand... It wasn't working yesterday, anyway sorry for disturbing
